# Generated by Django 2.2.3 on 2019-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='District Name')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nin',
            field=models.CharField(default=1000000001, max_length=200, verbose_name='NIN'),
            preserve_default=False,
        ),
    ]
