# Generated by Django 2.2.3 on 2019-08-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190830_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.District'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NIN'),
        ),
    ]
