# Generated by Django 2.2.3 on 2019-08-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donstituency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Constituency'),
        ),
    ]
