# Generated by Django 2.2.3 on 2019-08-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_donstituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='donstituency',
            new_name='constituency',
        ),
    ]
