# Generated by Django 2.2.3 on 2019-09-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190902_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Region'),
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Subcounty'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='constituency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Constituency'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Parish'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subcounty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Subcounty'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Village'),
        ),
        migrations.AddField(
            model_name='village',
            name='parish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Parish'),
        ),
    ]
