# Generated by Django 2.2.3 on 2019-09-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_paymentmode_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PaymentMode'),
        ),
    ]
