# Generated by Django 2.2.3 on 2019-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_subscription_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subcounty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='village',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentMode',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
