# Generated by Django 2.2.3 on 2019-09-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0011_owner_status'),
        ('users', '0015_auto_20190918_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=200)),
                ('business', models.CharField(max_length=200, verbose_name='Business intented to use the room for')),
                ('comment', models.TextField(verbose_name='Add a comment')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='region',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='subcounty',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='village',
            name='parish',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='BookStatus',
        ),
        migrations.DeleteModel(
            name='Constituency',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Subcounty',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.BookStatus', verbose_name='Room Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
