# Generated by Django 2.2.3 on 2019-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190920_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='person',
            field=models.CharField(default=1, max_length=200, verbose_name='Contact Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Contact Phone'),
            preserve_default=False,
        ),
    ]
