# Generated by Django 2.2.3 on 2019-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190920_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Contact Address'),
            preserve_default=False,
        ),
    ]
