# Generated by Django 2.2.3 on 2019-09-23 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_book_approve_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_approved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
