# Generated by Django 2.2.3 on 2019-09-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_tenantstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tenant_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.TenantStatus'),
        ),
    ]
