# Generated by Django 2.2.3 on 2019-09-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_complaintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200, verbose_name='Complain Title')),
                ('body', models.TextField(max_length=200, verbose_name='Complain Body')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('complain_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.ComplainType', verbose_name='Visible by')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Book', verbose_name='Room of Complain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
