# Generated by Django 2.2.3 on 2019-09-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190925_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='body',
            field=models.TextField(verbose_name='Complain Body'),
        ),
    ]
