# Generated by Django 2.2.3 on 2019-10-04 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_auto_20191004_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Business type'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('body', models.TextField(verbose_name='Product description')),
                ('cost', models.IntegerField(verbose_name='Buying Cost')),
                ('price', models.IntegerField(verbose_name='Selling Price')),
                ('photo', models.ImageField(blank=True, default='shop_photos/default.png', null=True, upload_to='shop_photos')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Shop', verbose_name='Shop of the Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
