# Generated by Django 2.2.3 on 2019-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20191004_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='phoduct_photos/default.png', null=True, upload_to='product_photos'),
        ),
    ]
