# Generated by Django 2.2.3 on 2019-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20191004_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sold at'),
        ),
    ]
