# Generated by Django 2.2.3 on 2019-09-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Building Constructor')),
                ('photo', models.ImageField(blank=True, default='acade_photos/default.png', null=True, upload_to='acade_photos')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Constructor Address')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Year', verbose_name='Year Established')),
            ],
        ),
        migrations.CreateModel(
            name='Acade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Acade Name')),
                ('photo', models.ImageField(blank=True, default='acade_photos/default.png', null=True, upload_to='acade_photos')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Acade Address')),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
