# Generated by Django 2.2.3 on 2019-09-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0003_auto_20190913_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='photo',
            field=models.ImageField(blank=True, default='constructor_photos/default.png', null=True, upload_to='constructor_photos'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Room Name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('acade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Acade', verbose_name='Building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Floor', verbose_name='Floor')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.RoomSize', verbose_name='Room Size')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
