# Generated by Django 2.2.3 on 2019-09-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0006_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='acade_owner.RoomStatus', verbose_name='Room Status'),
        ),
    ]
