# Generated by Django 2.2.3 on 2019-09-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0007_auto_20190917_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='acade_owner.RoomStatus', verbose_name='Room Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.RoomSize', verbose_name='Room Size'),
        ),
    ]
