# Generated by Django 2.2.3 on 2019-09-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0010_ownerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='acade_owner.OwnerStatus', verbose_name='Owner Status'),
        ),
    ]
