# Generated by Django 2.2.3 on 2019-09-23 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0011_owner_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acade',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('acade', 'floor', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('user', 'acade', 'floor', 'name')},
        ),
    ]
