# Generated by Django 2.2.3 on 2019-09-23 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0012_auto_20190923_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acade',
            name='no_of_floors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='acade',
            name='no_of_rooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
