# Generated by Django 2.2.3 on 2019-09-24 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0013_auto_20190923_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('amount_to_pay', models.IntegerField()),
                ('paid_by', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Month', verbose_name='Rent Month')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Year', verbose_name='Rent Year')),
            ],
        ),
    ]
