# Generated by Django 2.2.3 on 2019-09-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0014_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='amount_to_pay',
            field=models.IntegerField(verbose_name='Remaining Balance'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('phone', models.CharField(max_length=200, verbose_name='Employee Phone')),
                ('email', models.CharField(max_length=200, verbose_name='Employee Email')),
                ('address', models.CharField(max_length=200, verbose_name='Employee Address')),
                ('nin', models.CharField(max_length=200, verbose_name='National ID No.')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('acade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Acade', verbose_name='Building')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='acade_owner.OwnerStatus', verbose_name='Employee Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nin')},
            },
        ),
    ]
