# Generated by Django 2.2.3 on 2019-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0016_auto_20190924_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee_photos/default.png', null=True, upload_to='employee_photos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Employee Email'),
        ),
    ]
