# Generated by Django 2.2.3 on 2019-09-24 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0017_auto_20190924_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monthly_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(50000)]),
            preserve_default=False,
        ),
    ]
