# Generated by Django 2.2.3 on 2019-09-24 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0018_room_monthly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default=1, max_length=200, verbose_name='Job Title'),
            preserve_default=False,
        ),
    ]
