# Generated by Django 2.2.3 on 2019-09-25 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0019_auto_20190924_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='acade',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
