# Generated by Django 2.2.3 on 2019-09-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0020_acade_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acade',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
