# Generated by Django 2.2.3 on 2019-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0021_auto_20190925_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
