# Generated by Django 2.2.3 on 2019-09-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acade_owner', '0024_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clomplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('amount_to_pay', models.IntegerField(verbose_name='Remaining Balance')),
                ('paid_by', models.CharField(max_length=200)),
                ('received_by', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.Acade', verbose_name='Building')),
                ('bill_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.BillType', verbose_name='Building')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Month', verbose_name='Bill Month')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Year', verbose_name='Bill Year')),
            ],
        ),
    ]
