# Generated by Django 2.2.3 on 2019-09-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0025_clomplain_complaintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clomplain',
            name='acade',
        ),
        migrations.RemoveField(
            model_name='clomplain',
            name='bill_for',
        ),
        migrations.RemoveField(
            model_name='clomplain',
            name='month',
        ),
        migrations.RemoveField(
            model_name='clomplain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clomplain',
            name='year',
        ),
        migrations.DeleteModel(
            name='ComplainType',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acade_owner.BillType'),
        ),
        migrations.DeleteModel(
            name='Clomplain',
        ),
    ]
