# Generated by Django 2.2.3 on 2019-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0026_auto_20190925_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
