# Generated by Django 2.2.3 on 2019-09-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0027_means'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Means',
            new_name='Mean',
        ),
    ]
