# Generated by Django 2.2.3 on 2019-09-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0030_visitor_acade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Month', verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acade_owner.Year', verbose_name='Year'),
        ),
    ]
