# Generated by Django 2.2.6 on 2020-05-11 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acade_owner', '0034_auto_20200511_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
