from django.urls import path
from .views import *
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.home, name='owner-home'),
    path('room-chart/', views.room_chart, name='room-chart'),
    path('acade/', AcadeCreateView.as_view(), name='acade' ),
    path('acades/', AcadeListView.as_view(), name='acades' ),
	path('acade/<int:pk>/update', AcadeUpdateView.as_view(), name='update-acade' ),
	path('acade/<int:pk>', AcadeDetailView.as_view(), name='acade-details' ),
	path('room/', RoomCreateView.as_view(), name='room' ),
    path('rooms/', RoomListView.as_view(), name='rooms' ),
    path('rents/', RentListView.as_view(), name='rents' ),
    path('free_rooms/', FreeRoomListView.as_view(), name='free-rooms' ),
    path('bookings/', BookingListView.as_view(), name='booking' ),
    path('pending_bookings/', PendingBookingListView.as_view(), name='pending-booking' ),
    path('rejected_bookings/', RejectedBookingListView.as_view(), name='rejected-booking' ),
    path('tenants/', TenantListView.as_view(), name='tenants' ),
    path('current_tenants/', CurrentTenantListView.as_view(), name='current-tenants' ),
    path('previous_tenants/', PreviousTenantListView.as_view(), name='previous-tenants' ),
    path('occupied_rooms/', OccupiedRoomListView.as_view(), name='occupied-rooms' ),
    path('unavailable_rooms/', UnavailableRoomListView.as_view(), name='unavailable-rooms' ),
	path('update_room/<int:pk>', RoomUpdateView.as_view(), name='update-room' ),
	path('room/<int:pk>', RoomDetailView.as_view(), name='room-details' ),
	path('owner/', OwnerCreateView.as_view(), name='owner' ),
    path('owners/', OwnerListView.as_view(), name='owners' ),
    path('current_owners/', CurrentOwnerListView.as_view(), name='current-owners' ),
    path('previous_owners/', PreviousOwnerListView.as_view(), name='previous-owners' ),
	path('owner/<int:pk>/update', OwnerUpdateView.as_view(), name='update-owner' ),
	path('owner/<int:pk>', OwnerDetailView.as_view(), name='owner-details' ),
    path('update_employee/<int:pk>', EmployeeUpdateView.as_view(), name='update-employee' ),
    path('employee/', EmployeeCreateView.as_view(), name='employee' ),
    path('employees/', EmployeeListView.as_view(), name='employees' ),
    path('employee/<int:pk>', EmployeeDetailView.as_view(), name='employee-details' ),
    path('bill/', BillCreateView.as_view(), name='bill' ),
    path('bills/', BillListView.as_view(), name='bills' ),
    path('bill/<int:pk>', BillDetailView.as_view(), name='bill-details' ),
    path('visitor/', VisitorCreateView.as_view(), name='visitor' ),
    path('visitors/', views.visitors, name='visitors' ),
    path('bills_report/', views.bill_report, name='bills-report' ),
    path('selected_bills_report/', views.selected_bill_report, name='selected-bills-report' ),
    path('rents_report/', views.rent_report, name='rents-report' ),
    path('selected_rents_report/', views.selected_rent_report, name='selected-rents-report' ),
    path('visitor/<int:pk>/update', VisitorUpdateView.as_view(), name='update-visitor' ),
    path('bill/<int:pk>/update', BillUpdateView.as_view(), name='update-bill' ),
    url(r'^book/(?P<pk>\d+)/$', BookedRoomDetails.as_view(), name='booked-room-details' ),
    url(r'^tenant/(?P<pk>\d+)/$', TenantDetails.as_view(), name='tenant-details' ),
    url(r'^rent/(?P<id>\d+)/$', views.rent, name='rent'),
    url(r'^update_rent/(?P<id>\d+)/$', views.update_rent, name='update-rent'),
]
